### ISSUE TITLE
Check which version we should keep

### ISSUE THREAD

**Issue by wesleyhf** [kool-dev/docker-node#1]
Today there's **3 versions (10, 12, 14)** and **2 sub-versions (normal and QA)**, should we keep all these versions?

Maybe we can follow the LST and Current/Latest.

https://nodejs.org/en/

![image](https://user-images.githubusercontent.com/2936121/95138038-afe0a000-073f-11eb-988b-e1ed18a2e70f.png)

**Comment by dbpolito** [comment]
We keep 10 for our needs unfortunately a few projects still uses it.
