### ISSUE TITLE
Create recurrent build to always have latest patches/versions

### ISSUE THREAD

**Issue by fabriciojs** [kool-dev/docker-node#17]
Would be nice to have some scheduled action to routinely rebuild the images, staying always up-to-date with latest minors.

**Comment by rexdivakar** [comment]
Can u please elaborate more on this?

**Comment by fabriciojs** [comment]
@rexdivakar well, this is embarrassing. Sorry I totally missed notification about this comment of yours, almost a year ago.

I have just accomplished the intention of this task - we added a `schedule: 0 1 * * * ` trigger on the Github Action that builds/pushes the images; this way we will always have an up-to-date version on Hub Docker. 

Improvements still would be:

- Only build if versions actually changed (Node/npm)

**Comment by rexdivakar** [comment]
Cool no worries, appreciate the reply 😇
