### ISSUE TITLE
Updates to repo state

### ISSUE THREAD

**Issue by fabriciojs** [kool-dev/docker-node#37]
A couple of ideas I want to implement thinking in making simpler our images management;

Now:

- Add Node 18 version (alpha)
- Merge ALL extra images into one single `-full` version - with all CLIs/QA global tools we find necessary;
- Drop versions 10/12/14; keep only 16+

Future:

- Add Deno version (TBD - https://hub.docker.com/r/denoland/deno)

**Comment by fabriciojs** [comment]
Thumbs up or down please @kool-dev/core-members @kool-dev/firework

**Comment by danielsuguimoto** [comment]
@fabriciojs I'm not sure about dropping node 14 yet

**Comment by fabriciojs** [comment]
Just to clarify on dropping the old versions - the existing images would continue there as they are now; we would just stop rebuilding them/adding features as we move forward with the newer versions only.

**Comment by danielsuguimoto** [comment]
Oh, that kind of dropping! So, nevermind! This has my thumbs up!
